### ISSUE TITLE
bare variables

### ISSUE THREAD

**Issue by bhcopeland** [willthames/ansible-lint#116]
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{apache_modules}}'). This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

Would be great to get these deprecation warnings into lint!

**Comment by willthames** [comment]
It would, but someone will need to implement the check.

**Comment by willthames** [comment]
Fixed by #168 thanks to @Lowess
