### ISSUE TITLE
includes not searched for in appropriate directories

### ISSUE THREAD

**Issue by remleduff** [willthames/ansible-lint#120]
I have role with a handler that includes a file:

```
- name: Demo
  include: uninstall.yml
  when: condition.matched
```

"uninstall.yml" is in <role>/tasks and this is what ansible seems to expect.

However, ansible-lint throws a stacktrace:

> Traceback (most recent call last):
>   File "/usr/bin/ansible-lint", line 116, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "/usr/bin/ansible-lint", line 103, in main
>     matches = runner.run()
>   File "/usr/lib/python2.6/site-packages/ansiblelint/__init__.py", line 211, in run
>     skip_list=set(self.skip_list)))
>   File "/usr/lib/python2.6/site-packages/ansiblelint/__init__.py", line 115, in run
>     with open(playbookfile['path'], 'Ur') as f:
> IOError: [Errno 2] No such file or directory: u'/home/<omitted>/roles/demo/handlers/uninstall.yml'
>

**Comment by willthames** [comment]
Can you confirm `ansible-lint --version` and `ansible --version`

**Comment by willthames** [comment]
Ok, looks like including files in tasks from handlers is a new feature of ansible (a test playbook I wrote for this fails under 1.9 but not under 2.0). I typically use the Ansible libraries to look for includes in the right place but obviously I'm not quite modelling reality.

**Comment by remleduff** [comment]
Versions:

ansible-lint = 2.4.0
ansible = 2.0.0.2

I'll try your fix and report back!

**Comment by remleduff** [comment]
It's able to handle my playbook now using the handler_include_fix thanks!

**Comment by willthames** [comment]
Pushed as 2.4.1 to pypi
