### ISSUE TITLE
role_path is not loaded from ansible.cfg file

### ISSUE THREAD

**Issue by ssbarnea** [willthames/ansible-lint#124]
ansible-lint 2.4.1 fails to load roles from the `ansible.cfg` file which exist in the current directory. 

The roles_path looks like this:
roles_path = roles.galaxy:roles

Both roles.galaxy and roles are existing sub-directories. Ansible has not problem processing them, but linter ignores them.

If that was cause because you missed to split the path by double-colon you may also want to throw a lint error if the directories do not exist. Silent failures are not really cool :)

**Comment by willthames** [comment]
Please use the Issue Template when creating issues. 

This issue will be closed if not updated to use the Issue Template.

**Comment by willthames** [comment]
Closing, please resubmit using the Issue Template and with suitable test cases if this is still an issue.
