### ISSUE TITLE
AnsibleParseError generate full traceback dumps which break lint output consumers.

### ISSUE THREAD

**Issue by ssbarnea** [willthames/ansible-lint#125]
It seems that exceptions like the one documented on https://github.com/mschuchard/linter-ansible-linting/issues/3 do make almost impossible to integrate it with other apps, like the atom-linter.

I do agree the traceback dumps are very useful for debugging, they are not what you would expect from a normal tool execution.

Maybe adding a parameter for disabling them would sort this issue?

<img width="448" alt="screenshot 2016-03-21 10 23 54" src="https://cloud.githubusercontent.com/assets/102495/13921342/4a7fe96a-ef6f-11e5-92fc-6262d5c76944.png">

**Comment by ssbarnea** [comment]
```
---
- hosts:localhost
  roles:
    - name: xxx
```

**Comment by willthames** [comment]
Please use the issue template when raising issues.

It would be helpful in this case as to what you would expect ansible-lint to do with a broken playbook. You're correct that a stack trace isn't ideal, but neither do I want to just silence all possible error scenarios.

**Comment by willthames** [comment]
It might also make sense to run ansible-playbook --syntax-check on your playbooks as a pre-check to running ansible-lint

```
[ansible-lint (master)]$ ansible-playbook --syntax-check test/norole.yml -i localhost,
ERROR: Syntax Error while loading YAML script, test/norole.yml
Note: The error may actually appear before this position: line 3, column 8

- hosts:localhost
  roles:
       ^
```

And with the fix to `- hosts: localhost`:

```
[ansible-lint (master)]$ ansible-playbook --syntax-check test/norole.yml -i localhost,

playbook: test/norole.yml

ERROR: expected a role name in dictionary: {'name': 'xxx'}
```

**Comment by ssbarnea** [comment]
Here is another test case which triggers a stacktrace while passing the syntax-check:
```
---
- hosts:
  - localhost
  roles:
    - name: node
```

**Comment by willthames** [comment]
That fails `ansible-playbook --syntax-check` too:

```
ERROR! the role 'node' was not found in /home/wthames/src/ansible-lint/test/roles:/home/wthames/src/ansible-lint/test:/etc/ansible/roles

The error appears to have been in '/home/wthames/src/ansible-lint/test/norole2.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - name: node
      ^ here
```
