### ISSUE TITLE
Include ansible-playbook --syntax-check as part of the linting process

### ISSUE THREAD

**Issue by ssbarnea** [willthames/ansible-lint#127]
Please include `ansible-playbook --syntax-check` as a first stage of the linting process, and output its result using pep8 format, so it can be later consumed by other tools.

**Comment by mschuchard** [comment]
I just released a linter for ansible syntax checking.  That should hopefully satisfy your needs.

**Comment by willthames** [comment]
I'd use my 'Please use the Issue Template' canned response here, but probably easier to mark this wontfix.
