### ISSUE TITLE
`KeyError` when running 'ansible-lint'

### ISSUE THREAD

**Issue by allanlewis** [willthames/ansible-lint#162]
# Issue Type
- Bug report

# Ansible and Ansible Lint details
```
$ ansible --version
ansible 2.1.0.0
$ ansible-lint --version
ansible-lint 3.0.0
```
- ansible installation method: pip
- ansible-lint installation method: pip

# Actual Behaviour (Bug report only)
My playbook is large (40 roles), and it isn't clear what element is causing the issue.
```sh
$ ansible-lint site.yml
Traceback (most recent call last):
  File "/home/alewis/.local/bin/ansible-lint", line 128, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/alewis/.local/bin/ansible-lint", line 115, in main
    matches.extend(runner.run())
  File "/home/alewis/.local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 239, in run
    skip_list=set(self.skip_list)))
  File "/home/alewis/.local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 140, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/home/alewis/.local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 66, in matchtasks
    for task in ansiblelint.utils.get_normalized_tasks(yaml, file):
  File "/home/alewis/.local/lib/python2.7/site-packages/ansiblelint/utils.py", line 426, in get_normalized_tasks
    return [normalize_task(task, file['path']) for task in tasks]
  File "/home/alewis/.local/lib/python2.7/site-packages/ansiblelint/utils.py", line 378, in normalize_task
    task = normalize_task_v2(task)
  File "/home/alewis/.local/lib/python2.7/site-packages/ansiblelint/utils.py", line 291, in normalize_task_v2
    task_info = "%s:%s" % (task[FILENAME_KEY], task[LINE_NUMBER_KEY])
KeyError: '__file__'
$ ansible-playbook --syntax-check site.yml

playbook: site.yml
```

**Comment by allanlewis** [comment]
This only happens with Ansible>2:
```sh
$ ansible --version
ansible 1.9.6
  configured module search path = None
$ ansible-lint --version
ansible-lint 3.0.0
$ ansible-lint -p site.yml
site.yml:170: [EANSIBLE0006] yum used in place of yum module
...
```
I tried every version of Ansible available on PyPI from 2.1.0.0 downwards, and 1.9.6 was the first one that works. The only other thing complicating my setup is that I have both `ansible` and `ansible-lint` installed by the OS (Fedora 23).

**Comment by willthames** [comment]
The bit of code where the error is only runs with Ansible 2.0+ so it's not too surprising that 1.9.6 isn't having the problem.

Are you able to run custom ansible-lint - if so I'll create a patch that might at least allow us to work out what problem you're hitting.

**Comment by willthames** [comment]
I've actually pushed 3.0.1 to at least get some better output - you're hitting some kind of AnsibleParserError, just need to find out why. It should spit out a task dictionary now, that might help see where this is happening.

If you do get more information, please update this - particularly if you can reduce it down to a simple example test case.

**Comment by allanlewis** [comment]
I think I've found it: we're using a custom module defined in the `library` directory alongside the playbook. If I set `library = library` in `ansible.cfg`, `ansible-lint` works. So it seems like `ansible-lint` needs to always include `./library` in its module search path.

**Comment by willthames** [comment]
I didn't even realise that was a thing (playbooks can contain library directories)

**Comment by willthames** [comment]
3.0.2rc1 might contain a fix if you want to try it.

**Comment by willthames** [comment]
ansible 3.1.0 is released with this change
