### ISSUE TITLE
[ANSIBLE0012] Handlers should be allows to run shell/command entries without when

### ISSUE THREAD

**Issue by robinro** [willthames/ansible-lint#165]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

ansible --version: 2.1
ansible-lint --version: 3.0.1

- ansible installation method: source
- ansible-lint installation method: pip

# Desired Behaviour

ANSIBLE0012 checks for usage of `shell` or `command` without `when`, `changed_when`, ...
While this represent good practice for tasks, it is not needed for handlers, which have an implicit `when: original_task|changed`.

Thus handlers should be excluded from this check.

# Actual Behaviour (Bug report only)

[ANSIBLE0012] Commands should not change things if nothing needs doing
.../roles/foo/handlers/main.yml:3
Task/Handler: run shell command

**Comment by willthames** [comment]
Yes, you're quite right - expect a patch in the next day or so.

**Comment by robinro** [comment]
Thanks.

btw: ansible-lint is a great tool! We started running it in our CI setup and it gave some good hints already.

**Comment by willthames** [comment]
3.1.0rc1 released for testing purposes

**Comment by willthames** [comment]
If you like ansible-lint, you may also like ansible-review (I spotted this bug in ansible-review a while back but because you can tell ansible-review what types of files to run a lint check against, I could avoid the bug at the ansible-review end - I didn't think to fix it here at that time)

**Comment by robinro** [comment]
Thanks for the fix!
