### ISSUE TITLE
question: ANSIBLE0010 desired behavior

### ISSUE THREAD

**Issue by mschuchard** [willthames/ansible-lint#169]
Is the intention of ANSIBLE0010 to only act on the yum, apt, and package modules as written [here](https://github.com/willthames/ansible-lint/blob/master/lib/ansiblelint/rules/PackageIsNotLatestRule.py#L32), or should it also apply to other package managers like gem, pip, npm, etc.?

**Comment by willthames** [comment]
I wrote it with OS package managers in mind, but I have zero problems with it being extended to work with language package managers.

**Comment by mschuchard** [comment]
Thanks for the info.
