### ISSUE TITLE
ansible-lint crashes with KeyError for the color 'magenta'

### ISSUE THREAD

**Issue by Cull-Methi** [willthames/ansible-lint#171]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version: 2.0.1.0
ansible-lint --version: 3.1.1
```

- ansible installation method:  source
- ansible-lint installation method: source (github)

# Desired Behaviour

Exception should not occur

# Actual Behaviour (Bug report only)

Ansible-lint crashes with a KeyError on any playbook file I've tried:

```
ansible-lint configure-already-installed.yml
Traceback (most recent call last):
  File "/home/mitchell.usher/gits/ansible-lint/bin/ansible-lint", line 132, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/mitchell.usher/gits/ansible-lint/bin/ansible-lint", line 122, in main
    print(formatter.format(match, options.colored))
  File "/home/mitchell.usher/gits/ansible-lint/lib/ansiblelint/formatters/__init__.py", line 16, in format
    stringc(match.line, 'magenta'))
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.0.1.0-py2.7.egg/ansible/utils/color.py", line 72, in stringc
    return u"\033[%sm%s\033[0m" % (codeCodes[color], text)
KeyError: 'magenta'

```
It works properly if I use the --nocolor flag

Running on xubuntu 14.04

**Comment by Lowess** [comment]
@Cull-Methi thanks for filing this ticket.

@willthames I can look into this tomorrow if you want.

**Comment by Lowess** [comment]
I found out why you are getting this error. ansible-lint colors are using a color map from the ansible project.

The `magenta` color was added in version 2.0.2.0 and before that, only the `purple ` color was available.

I will send a PR and reference this ticket in it.

**Comment by tchia04** [comment]
I filed a similar issue at https://github.com/willthames/ansible-lint/issues/177 for Mac
