### ISSUE TITLE
Have to use ansible-lint --nocolor on Mac in order it to get it working

### ISSUE THREAD

**Issue by tchia04** [willthames/ansible-lint#177]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

ansible --version
ansible 1.9.4
  configured module search path = /usr/share/ansible

ansible-lint --version
ansible-lint 3.2.1

- ansible installation method: pip, OS package
- ansible-lint installation method: pip, OS package

 pip list | grep -i ansible
ansible (1.9.4)
ansible-lint (3.2.1)

# Desired Behaviour
I expected ansible-lint to work right after installation on a simple playbook

# Actual Behaviour (Bug report only)

Right after installation, I tried ansible-lint on a playbook.yml file and got the following stack trace. After debugging for a while, I found I can turn off the color and get it working. By default it should work out of the box. Maybe change the default to nocolor? 

ansible-lint zookeeper.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 135, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 125, in main
    print(formatter.format(match, options.colored))
  File "/Library/Python/2.7/site-packages/ansiblelint/formatters/__init__.py", line 15, in format
    stringc(match.linenumber, 'cyan'),
  File "/Library/Python/2.7/site-packages/ansible/color.py", line 69, in stringc
    return "\033["+codeCodes[color]+"m"+text+"\033[0m"
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by tchia04** [comment]
Has anyone got anisble-lint to work with color on Mac?

**Comment by willthames** [comment]
As far as I can tell, it's nothing to do with OS X, it's that ansible 1.9's `stringc` doesn't work it if you pass it an `int` (like linenumber). I'll wrap the linenumbers in `str`

**Comment by willthames** [comment]
I've release 3.2.2rc1 for testing - if you confirm it works I'll commit the change.

`pip install --pre --no-deps --upgrade ansible-lint`

should do the upgrade

**Comment by tchia04** [comment]
It kind of worked. It got rid of the "TypeError: cannot concatenate 'str' and 'int' objects" error message and now complains about "TypeError: cannot concatenate 'str' and 'dict' objects"


Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 135, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 125, in main
    print(formatter.format(match, options.colored))
  File "/Library/Python/2.7/site-packages/ansiblelint/formatters/__init__.py", line 16, in format
    stringc(match.line, 'purple'))
  File "/Library/Python/2.7/site-packages/ansible/color.py", line 69, in stringc
    return "\033["+codeCodes[color]+"m"+text+"\033[0m"
TypeError: cannot concatenate 'str' and 'dict' objects

**Comment by willthames** [comment]
I can't reproduce that with ansible-lint 3.2.2rc1 and ansible 1.9.4 on OS X.

Can you provide an example playbook and rule that it's failing with?

Or run it with 

```
ipython --pdb `which ansible-lint` -- playbook.yml
```

and at the debugger, do 

```
p color
p text
```

(you may need to install ipython but it's the easiest way to get to a debugger on failure)

**Comment by tchia04** [comment]
Hi Will, 

I am not having any success to install the ipython even with --ignore-installed like (sudo pip install ipython --ignore-installed). Getting a lot of "Operation not permitted" 

However here is a playbook you can use. I think it's failing on the sudo is deprecated rule since when I comment out the "sudo: yes" then I don't get the error. 

<pre>
- name: Alestic APT Key
  tags: ['snapshots']
  apt_key:
    id: kkkkkkk
    keyserver: keyserver.ubuntu.com
    state: present
#  sudo: yes
  when: ansible_distribution == "Ubuntu"
</pre>


Without "sudo: yes" in the playbook,
ansible-lint ubuntu.yml -v
Examining ubuntu.yml of type playbook

With "sudo: yes" in the playbook and using "ansible-lint ubuntu.yml"
<pre>
$ ansible-lint ubuntu.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 135, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 125, in main
    print(formatter.format(match, options.colored))
  File "/Library/Python/2.7/site-packages/ansiblelint/formatters/__init__.py", line 16, in format
    stringc(match.line, 'purple'))
  File "/Library/Python/2.7/site-packages/ansible/color.py", line 69, in stringc
    return "\033["+codeCodes[color]+"m"+text+"\033[0m"
TypeError: cannot concatenate 'str' and 'dict' objects
</pre>

With "sudo: yes" in the playbook and using "ansible-lint ubuntu.yml -p"

$ ansible-lint ubuntu.yml -p
ubuntu.yml:3: [EANSIBLE0008] deprecated sudo feature

**Comment by willthames** [comment]
Ok, thanks for the improved bug report. It seems that `SudoRule` returns a `line` which is a `dict` (I was expecting `line` to be a `str`). The formatters now cope with that case.

This bug only affects Ansible 1.9 (the stringc routine must be more robust in 2.0 onwards).

3.2.2 has been pushed containing this fix
