### ISSUE TITLE
new release setup.py still 3.2.2

### ISSUE THREAD

**Issue by pnemade** [willthames/ansible-lint#182]
# Issue Type
- Bug report

Today's released tarball on github is labled as 3.2.4 whereas setup.py is showing 3.2.2 version. Thus, fedora package update failed as egginfo is 3.2.2 versioned.

**Comment by willthames** [comment]
Argh, I'd updated version.py but not committed it before tagging 3.2.4

I'll just release 3.2.5 and update this when done.

**Comment by willthames** [comment]
3.2.5 has been released, tagged and uploaded to pypi

**Comment by pnemade** [comment]
:+1:
