### ISSUE TITLE
Ansible-lint fails on Ubuntu 16.04 in Atom

### ISSUE THREAD

**Issue by ludovicc** [willthames/ansible-lint#194]
# Issue Type
- Bug report

I'm using Ansible lint from Atom 0.10.0 and its package linter-ansible-linting
Python 3 is the default on my system.

ansible-lint fails with some syntax error on except, I beleive the correct syntax should be 'except IOError as e'.

# Ansible and Ansible Lint details

```
ansible --version
  ansible 2.1.1.0
ansible-lint --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 30, in <module>
    import ansiblelint
  File "/usr/local/lib/python3.5/dist-packages/ansiblelint/__init__.py", line 128
    except IOError, e:
                  ^
SyntaxError: invalid syntax

pip show ansible-lint
  Version: 3.2.5
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

# Actual Behaviour (Bug report only)

```
Uncaught (in promise) Error: Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 30, in <module>
    import ansiblelint
  File "/usr/local/lib/python3.5/dist-packages/ansiblelint/__init__.py", line 128
    except IOError, e:
                  ^
SyntaxError: invalid syntax
    at ChildProcess.<anonymous> (/home/ludovic/.atom/packages/linter-ansible-linting/node_modules/sb-exec/lib/index.js:41:20)
```

**Comment by gundalow** [comment]
This looks like a py3 issue, the following may be useful:

http://docs.ansible.com/ansible/developing_modules_python3.html

**Comment by willthames** [comment]
There is a py3 branch but until Ansible is python 3 compliant, ansible-lint
will fail because its dependencies fail.

**Comment by ludovicc** [comment]
I have found that ansible-lint and ansible fail because of Python3. Can you update the documentation in README.md, the command to launch to install should be ''pip2.7 install ansible-lint'

**Comment by ludovicc** [comment]
PR #195 should fix that

**Comment by willthames** [comment]
#195 merged.
