### ISSUE TITLE
always_run is deprecated in Ansible 2.2

### ISSUE THREAD

**Issue by jbscare** [willthames/ansible-lint#220]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

- ansible 2.2.0.0
- ansible-lint 3.4.3
- ansible installation method: source
- ansible-lint installation method: source

# Desired Behaviour

always_run is deprecated in Ansible 2.2, so it'd be nice if ansible-lint caught it and complained.

**Comment by willthames** [comment]
This is quite a simple rule to write if you'd like to write it - you're basically checking for

```
'always_run' in task
```
using the `matchtask` check - not hugely different to `TaskHasNameRule.py`

**Comment by willthames** [comment]
v3.4.10 is now available with this fix.
