### ISSUE TITLE
Ansible dependency

### ISSUE THREAD

**Issue by retr0h** [willthames/ansible-lint#222]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
[jodewey:~/git/molecule] docs-usage-fixup(+3/-1)+ ± ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
[jodewey:~/git/molecule] docs-usage-fixup(+3/-1)+ ± ansible-lint --version
ansible-lint 3.2.5
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

Ansible should not be installed on my system by simply installing ansible-lint.

# Actual Behaviour (Bug report only)

Ansible gets installed when pip installing `ansible-lint`.  Since one may wish to use other versions of ansible.  Having ansible listed as a dependency, pulls in a potentially unwanted version, depending on the order in which pip is executed.

```
[jodewey:~/git/molecule] docs-usage-fixup(+3/-1)+ ± pip show ansible-lint
Name: ansible-lint
Version: 3.2.5
Summary: checks playbooks for practices and behaviour that could potentially be improved
Home-page: https://github.com/willthames/ansible-lint
Author: Will Thames
Author-email: will@thames.id.au
License: MIT
Location: /Users/jodewey/.pyenv/versions/2.7.12/envs/molecule-env-2.7.12/lib/python2.7/site-packages
Requires: pyyaml, ansible
```

**Comment by willthames** [comment]
The alternative is that ansible-lint fails because ansible is not installed. 

I want people to be able to do `pip install ansible-lint` in a virtualenv or similar and for it to just work.

**Comment by willthames** [comment]
If you want a different version, install it first or just `pip install --upgrade ansible=2.x.y` (to a lower version if necessary)

**Comment by retr0h** [comment]
> The alternative is that ansible-lint fails because ansible is not installed.

Yeah, I figured that would be the response.  To play devils advocate.  People would not be using `ansible-lint`, if they were not already using `ansible`.  I highly doubt they simply install `ansible-lint` and call it a day.  However, I respect your decision, was worth a shot 😄

**Comment by willthames** [comment]
Thanks, I'll close this :)
