### ISSUE TITLE
Support for defaults, vars, and meta

### ISSUE THREAD

**Issue by asmartin** [willthames/ansible-lint#228]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
ansible 2.2.0.0
ansible-lint 3.4.8
```

- ansible installation method: OS package
- ansible-lint installation method: pip

# Desired Behaviour

Thank you for creating ansible-lint - this looks like a fantastic tool for supporting best practices in ansible playbooks. I would really like to be able to lint vars files in `defaults/main.yml` as well as `vars/main.yml` and other files in the playbook - is it possible to support checking these files as well as tasks? 

Moreover, I see that ansible-lint supports roles, but I have several roles in my `meta/main.yml` but it does not appear to be finding problems in these dependent roles. Is checking `meta/main.yml` currently supported?

Thanks!

**Comment by willthames** [comment]
Hi Andrew, ansible-lint does not support meta/main.yml etc.

However, https://github.com/willthames/ansible-review is designed for that kind of functionality (a lot of its checks are based on ansible-lint checks)

http://willthames.github.io/2016/06/28/announcing-ansible-review.html

**Comment by asmartin** [comment]
Hi Will,

Thanks for the quick reply! Is it possible to have ansible-review output its findings and use another tool for the actual code review? I have another tool that I prefer using for the review itself, so I would only need ansible-review to check syntax and perform linting. Is this possible?

**Comment by willthames** [comment]
Not really 100% sure what you mean - all ansible-review does by default is print some output and exit with an error code if there are errors - you can use this to be an input to a review, or as a test at CI time, or you can just use the underlying ansiblereview library in python code elsewhere.

ansible-review is designed to be an input to a code review process rather than as a review tool as a whole, if that makes sense.

**Comment by asmartin** [comment]
Ah okay, thanks for the clarification. I'll give it a try and let you know
if I have any questions!

**Comment by willthames** [comment]
I'll close this issue - feel free to raise issues on ansible-review though if you have questions.
