### ISSUE TITLE
Instructions for installing from source

### ISSUE THREAD

**Issue by udondan** [willthames/ansible-lint#257]
Just wanted to install ansible-lint from source and noticed the instructions in the README are not accurate:

```
git clone https://github.com/willthames/ansible-lint
export PYTHONPATH=$PYTHONPATH:`pwd`/ansible-lint/lib
export PATH=$PATH:`pwd`/ansible-lint/bin
```
There is no `bin` directory. I now just symlinked `ansible-lint/lib/ansiblelint/main/__init__.py` into my users bin dir.

    ln -s ansible-lint/lib/ansiblelint/main/__init__.py $HOME/bin/ansible-lint

**Comment by udondan** [comment]
Which of course doesn't work. :) What would be the correct way of installing from source (without using easy_install)?

**Comment by vegai** [comment]
Have you tried 

```
python setup.py install --user
```

**Comment by willthames** [comment]
See also #254 and #259

**Comment by udondan** [comment]
@vegai I'm fine with the symlink approach. Just docs need to be updated which will be covered with #259. Thanks
