### ISSUE TITLE
ansible-lint ignores -x parameters except the last one

### ISSUE THREAD

**Issue by KellerFuchs** [willthames/ansible-lint#279]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

ansible-2.3.2.0 & ansible-lint-3.4.15, installed via pip

# Desired Behaviour

`-x foo,bar -x baz` should result in all of `foo`, `bar` and `baz` being ignored.

# Actual Behaviour (Bug report only)

`-x foo,bar -x baz` results in only `baz` being ignored.

See [this build](https://travis-ci.org/hashbang/admin-tools/builds/272718491#L493) vs. [this one](https://travis-ci.org/hashbang/admin-tools/builds/272720279#L493)

**Comment by retr0h** [comment]
ping

**Comment by KellerFuchs** [comment]
@retr0h I submitted a patch and @willthames merged it; please confirm that fixes your issue  :)
