### ISSUE TITLE
Feature request - configuration file

### ISSUE THREAD

**Issue by zigarn** [willthames/ansible-lint#283]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
$ ansible --version
ansible 2.4.0.0
$ ansible-lint --version
ansible-lint 3.4.15
```

- ansible installation method: OS package
- ansible-lint installation method: pip

# Desired Behaviour

Be able to set configuration in a config file, with a default like `.ansible-lint` in which we can set some options like the skip list or exclude list.
This way, it's not necessary to put those options on the command line each time we call `ansible-lint`.

**Comment by njenan** [comment]
@zigarn I opened a PR to add this feature #290 please take a look.

**Comment by brandonkal** [comment]
Looks like this can be closed
