### ISSUE TITLE
Vars directory not included when linting a role

### ISSUE THREAD

**Issue by msuringa** [willthames/ansible-lint#293]
# Issue Type
- Feature request

# Ansible and Ansible Lint details
```
ansible --version
  ansible 2.3.1.0
ansible-lint --version
  ansible-lint 3.4.16
```

- ansible installation method: OS package
- ansible-lint installation method: pip

# Desired Behaviour

When running ansible-lint on a particular role, I would expect it to also check the vars (and possibly defaults) directory for rule violations. At the moment this is not the case as the directories that are checked are set to tasks, handlers and meta.
Is there any specific reason why these directories are excluded?

The main reason I would like this feature is because we do certain lookups in variables, and these can not be checked at this time.

**Comment by msuringa** [comment]
In case this is a desired feature, I have already created a pull request with the change: https://github.com/willthames/ansible-lint/pull/294

**Comment by willthames** [comment]
As mentioned in #294, please use ansible-review for this task
