### ISSUE TITLE
Add minimum requirement info

### ISSUE THREAD

**Issue by widyono** [willthames/ansible-lint#47]
Hi, usage of "contains_vars" (in utils.py line 89) means one must have at least ansible 1.8.x.

Could you please insert a note in README.md (for example) stating such minimum requirement? Or, optionally, allow use with ansible 1.7.x by replacing line 89 in lib/ansiblelint/utils.py with:

if "$" in child['path'] or "{{" in child['path']:

**Comment by willthames** [comment]
Fixed in #48
