### ISSUE TITLE
Ansible's unarchive module is not always analogous to the tar command

### ISSUE THREAD

**Issue by ericwb** [willthames/ansible-lint#58]
If I have a task that creates an archive (instead of expanding) there is no Ansible equivalent module to my knowledge that can accomplish this, yet the linter is reporting ANSIBLE0006.

For example:
  shell: "/bin/tar czf {{support_log_root}}/{{timestamp}}/support.tgz *"

**Comment by willthames** [comment]
See #40 for to skip ansible-lint for this task

(I should update the docs though)

**Comment by ericwb** [comment]
Thanks!

Also appears this is a duplicate of https://github.com/willthames/ansible-lint/issues/23
