### ISSUE TITLE
is this listed in available atom packages?

### ISSUE THREAD

**Issue by aioue** [willthames/ansible-lint#65]

**Comment by willthames** [comment]
Given that I don't know what an atom package is, I'm going to confidently reply "No."

If there's anything needed at a code level to achieve this, please submit a PR. If it's just a matter of me submitting a form somewhere, please point me at appropriate documentation

**Comment by aioue** [comment]
Thank you for the quick reply. Apologies, I got my tabs mixed up meant to comment on another [Atom](https://atom.io/) project. Thanks for you time.
