### ISSUE TITLE
Should linter consider .yml incorrect in favor of .yaml?

### ISSUE THREAD

**Issue by edunham** [willthames/ansible-lint#72]
http://www.yaml.org/faq.html says "please use .yaml whenever possible". Would a PR to make ansible-lint warn when files have `.yml` rather than `.yaml` extensions be welcome?

**Comment by edunham** [comment]
possibly relevant: https://github.com/willthames/ansible-lint/pull/69

**Comment by smiller171** [comment]
most ansible docs use .yml. This is the first time I have heard .yaml is proffered by anyone

**Comment by willthames** [comment]
I won't be making (or including) a rule for this - I agree with @smiller171, even though I'm happy to incorporate #69. 

But it should be a simple enough task to create (and share if you like) your own rules though - if there's anything in ansible-lint that is preventing that working as a custom rule, let me know.
