### ISSUE TITLE
examples.yml clash with README

### ISSUE THREAD

**Issue by mschuchard** [willthames/ansible-lint#76]
I was just finishing up an atom package for ansible-lint when I tested it against the examples.yml and noticed that in ansible-lint 2.1.3 the following is NOT thrown despite what the README states:

[ANSIBLE0001] Old style (${var}) brackets
examples/example.yml:10
    action: command echo ${oldskool}

**Comment by willthames** [comment]
Because the old variable templating was removed such a long time ago, and ansible-playbook gave deprecation warnings, the use for this rule expired, so I deleted it. 

The README needs an update - pull requests welcomed or I'll get around to it at some point!

**Comment by mschuchard** [comment]
Thanks for the info.  I would fork and pr on this except it is small so I am sure the next time you update the README you could handle it easier.
