### ISSUE TITLE
Feature Request - Add exclude-paths option

### ISSUE THREAD

**Issue by sigmavirus24** [willthames/ansible-lint#80]
I work on a project that is slowly integrating ansible-lint into the standards. We're working on doing this on a per-role basis and what we'd like to do is have a list of paths that we don't check and slowly remove them from that list until we have no more left.

Would the project be open to a command-line option that would allow us to do something like

```
$ ansible-lint --exclude-paths=roles/roleA,roles/roleB,roles/roleC *.yml
```

Perhaps instead something like

```
$ ansible-lint --exclude-roles=roleA,roleB,roleC *.yml
```

I'd be happy to work on implementing this.

**Comment by willthames** [comment]
Hi, that sounds reasonable to me - if you want to work on it, I'd be happy to include it.

**Comment by sigmavirus24** [comment]
Which version do you prefer, `--exclude-paths`, `--exclude-roles`, something else?

**Comment by willthames** [comment]
`--exclude-paths` seems more flexible (e.g. you can exclude `role/roleA/tasks/non-compliant-include.yml`)

**Comment by sigmavirus24** [comment]
:+1: I'll try to tackle this tomorrow
