### ISSUE TITLE
TypeError during linting if playbook has no tasks

### ISSUE THREAD

**Issue by sehqlr** [willthames/ansible-lint#90]
If you run the ansible-lint on a playbook that doesn't have any tasks in it, it throws a TypeError.
The file in question: https://github.com/CiscoCloud/microservices-infrastructure/blob/master/terraform.sample.yml
The error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 113, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 100, in main
    matches = runner.run()
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 202, in run
    skip_list=set(self.skip_list)))
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 114, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 60, in matchtasks
    if 'skip_ansible_lint' in task.get('tags', []):
TypeError: argument of type 'NoneType' is not utterable
```

I can try to make a PR to fix this, but I wanted to know what the expected behavior should be. Thanks

**Comment by shaleh** [comment]
Around line 60 of lib/ansiblelint/__init__.py:

    for task in ansiblelint.utils.get_action_tasks(yaml, file):
        tags = task.get('tags', [])  # this issue is tags is None, not an empty list
        if tags and 'skip_ansible_lint' in tags:  # so check tags first
            continue

**Comment by willthames** [comment]
It's not that there are no tasks, it's that the task has an empty tags block: 

https://github.com/CiscoCloud/microservices-infrastructure/blob/b99a6a3ab660dcaab23505dcaf61cf0f516424fa/roles/common/tasks/main.yml#L80

**Comment by willthames** [comment]
Thanks for the bug report, fixed (with test) now.
