### ISSUE TITLE
Bug in ansible-lint current and previous version

### ISSUE THREAD

**Issue by EricTRA** [willthames/ansible-lint#98]
Whenever I ran ansible-lint I got a Python error referencing that a type could not be NoneType. Drilling down to it I could 'bypass' it by commenting out the 'if' in __init__.py at line 60 and 61.
Yesterday I found the root cause to be a 'tags:' part without any items in it. 

I believe ansible-lint should be throwing an error with regards to the empty tags part instead of throwing a Python error and exit. 

I caught this when I started using Ansible 2.0 which throws the error that 'Tags must be in a list'

**Comment by willthames** [comment]
Can you confirm your ansible-lint version?

I fixed ansible-lint to handle empty tags after issue #90 was raised. I guess I just need to check if those changes made it to pip

**Comment by EricTRA** [comment]
Hi Will,

Sure.. here goes:

~ ➤ ansible-lint --version



ansible-lint 2.3.0
~ ➤

Thank you for a swift reply :-)

Kind regards,

Eric

**Comment by willthames** [comment]
Ok, 2.3.2 was the latest. But didn't contain the fix. 

I've pushed 2.3.3 to pypi now which does contain the fix.

**Comment by EricTRA** [comment]
Thank you for a fast fix Will

Have a nice weekend!

Kind regards,

Eric

**Comment by siddharthist** [comment]
Looks like this issue could be closed @willthames

**Comment by EricTRA** [comment]
Yes, confirmed working now. Thanks!

**Comment by willthames** [comment]
Thanks @siddhartist and @EricTRA
